#!/usr/bin/env python
"""
#-----------------------------------------------------------------------
read-rcgroups -- read new messages on rcgroups.com

rcgroups sends a set of nightly emails (one per subscribed thread)
telling you what's new to be read.  this program grabs those messages,
opens the threads in your browser, and deletes the messages.  Don't
be alarmed if it opens a lot of tabs.

If you use gmail, add this filter:
    Matches: from:(rcgroups.com@vsobr.com)
    Do this: Skip Inbox, Apply label "[Gmail]/rcgroups"

usage: read-rcgroups [mailserver]

This is part of the mailtools package : (c) 2015 Mark Harrison
https://github.com/marhar/mailtools   :     Share and Enjoy!
"""

#-----------------------------------------------------------------------
import sys,time,os,email
from subprocess import Popen, PIPE
import mailcfg

#-----------------------------------------------------------------------
def doopen(url):
    """open this url in a browser
       currently works for mac.  if you're on another system let me
       know what works!
    """
    os.system("open '%s'"%(url))
    #time.sleep(.25)  # this delay seems to makes opening smoother

#-----------------------------------------------------------------------
def contains(re,s):
    """does s contain this re?"""
    mm=re.search(x)
    if mm:
        res=mm.group(1)
    else:
        res=None
    return res

#-----------------------------------------------------------------------
def url(s):
    """look for the strings that indicate unread forums or threads.
       rcgroups keeps changing the message format, so we adjust whenever
       we notice things not working.
    """
    msg = email.message_from_string(s)
    for part in msg.walk():
        if part.get_content_type() == 'text/plain':
            for line in part.get_payload(decode=True).split('\n'):
                line=line.strip()
                if line.startswith('http://url5878.vsobr.com'):
                    # urllib2 dies with HTTP Error 403: Forbidden
                    # so for now call out to curl
                    #     import urllib2
                    #     response = urllib2.urlopen(url)
                    #     for line in response.info().headers:
                    #         print line.strip()

                    process = Popen(['curl', '-I', line], stdout=PIPE, stderr=PIPE)
                    stdout, stderr = process.communicate()
                    for cline in stdout.split('\n'):
                        cline=cline.strip()
                        fields=cline.split()
                        if len(fields) >= 2 and fields[0]=='Location:':
                            rv=fields[1]+'&goto=newpost'
                            return rv
                    return None
                if line.startswith('https://www.rcgroups.com'):
                    return line
#-----------------------------------------------------------------------
def main():
    """Our main business is not to see what lies dimly at a
       distance, but to do what lies clearly at hand.
          --Thomas Carlyle
    """

    showstart()
    logger = open("rcreader.log", "a")
    logger.write("-----------\n")
    logger.flush()
    if len(sys.argv) > 1:      # max messages to process (including dupes)
        N=int(sys.argv[1])
    else:
        N=200

    if len(sys.argv) > 2:      # default to gmail
        server=sys.argv[2]
    else:
        server='gmail'

    m=mailcfg.imapserver(server)
    rc,data=m.select('[Gmail]/rcgroups') # we filter to here on gmail
    mailcfg.ok(rc,data)

    rc,data=m.search(None, '(FROM "rcgroups.com@vsobr.com")')
    mailcfg.ok(rc,data)

    seen={}
    nshown=0
    nskipped = 0
    nerrored = 0
    totmsgs=len(data[0].split())
    #print 'messages:',totmsgs
    i = 0
    for msgno in data[0].split():
        i += 1
        rc,data=m.fetch(msgno,'(RFC822)')
        mailcfg.ok(rc,data)
        body=email.message_from_string(data[0][1])
        h=url(str(body))
        if h is None:
            nerrored += 1
            show(i, totmsgs, nskipped, "E", runstate)
        elif seen.has_key(h) == False:
            nshown += 1
            seen[h] = 1
            logger.write("open '" +h + "'\n")
            logger.flush()
            if DOIT: doopen(h)
            show(i, totmsgs, nskipped, ".", runstate)
        else:
            show(i, totmsgs, nskipped, "o", runstate)
            nskipped += 1
            #print '# (skip)', h
        if DOIT: m.store(msgno, '+FLAGS', '\Deleted')

        if nshown >= N:
            print '*** stopped after first %d, %d left'%(N,totmsgs-N)
            break

    sys.stdout.write("\n%d opened %d skipped\n" % (nshown, nskipped))
    sys.stdout.write("\n%d errored\n" % (nerrored))
    m.close()
    m.logout()

def ttt(s):
    """write string to screen"""
    sys.stdout.write(s)
    sys.stdout.flush()

def showstart():
    ttt("\033[2J\033[H")

def show(i, totmsgs, nskipped, ch, extra):
    if not DOIT:
        return
    WIDTH = 10
    ttt("\033[H%d %d %d %s"%(totmsgs, i, nskipped, extra))
    cc = (i - 1) // WIDTH
    rr = (i - 1) % WIDTH
    rr += 1
    cc += 2
    ttt("\033[%d;%dH%s"%(cc,rr,ch))
    time.sleep(DELAY)

#-----------------------------------------------------------------------
DELAY=0  # make larger for debugging or for slow computer
DOIT=True
#DOIT=False  # uncomment for testing
if (not DOIT):
    runstate = "DRY RUN MODE"
else:
    runstate = ""

try:
    main()
except KeyboardInterrupt:
    pass
