#!/usr/bin/env python
"""
#-----------------------------------------------------------------------
read-rcgroups -- read new messages on rcgroups.com

rcgroups sends a set of nightly emails (one per subscribed thread)
telling you what's new to be read.  this program grabs those messages,
opens the threads in your browser, and deletes the messages.  Don't
be alarmed if it opens a lot of tabs.

usage: read-rcgroups [mailserver]

This is part of the mailtools package : (c) 2015 Mark Harrison
https://github.com/marhar/mailtools   :     Share and Enjoy!
"""

#-----------------------------------------------------------------------
import sys,re,time,os,email
import mailcfg

#-----------------------------------------------------------------------
def open(url):
    """open this url in a browser
       currently works for mac.  if you're on another system let me
       know what works!
    """
    os.system("open '%s'"%(url))
    time.sleep(.25)  # this delay seems to makes opening smoother

#-----------------------------------------------------------------------
# handy re's for rcgroups email
#-----------------------------------------------------------------------
re_http=re.compile(r'^(http://.*)$')
re_subj=re.compile(r'Subject: (.*)')
re_thread=re.compile(r'^(You are subscribed to the thread.*)')
re_forum=re.compile(r'^You are subscribed to the forum[^,]*, (.*)')

#-----------------------------------------------------------------------
def contains(re,s):
    """does s contain this re?"""
    mm=re.search(x)
    if mm:
        res=mm.group(1)
    else:
        res=None
    return res

#-----------------------------------------------------------------------
def url(s):
    """look for the strings that indicate unread forums or threads.

       this is a bunch of hacky stuff that looks in the email body
       and tries to figure out what's not read.  Hope rcgroups never
       changes the body format!  Even better that they include a
       nice json summary.
    """

    http=None
    for x in s.split('\n'):
        x=x.replace('\r','')
        mm=re_http.search(x)
        if mm:
            http=mm.group(1)
            http=http.replace(' ','')
            http+='&goto=newpost'
            break   # must break, or you will pick up the unsubscribe link

    return http

#-----------------------------------------------------------------------
def main():
    """Our main business is not to see what lies dimly at a
       distance, but to do what lies clearly at hand.
          --Thomas Carlyle
    """
    if len(sys.argv) > 1:      # default to gmail
        server=sys.argv[1]
    else:
        server='gmail'

    m=mailcfg.imapserver(server)
    rc,data=m.select('[Gmail]/rcgroups') # we filter to here on gmail
    mailcfg.ok(rc,data)

    rc,data=m.search(None, '(FROM "web@rcgroups.com")')
    mailcfg.ok(rc,data)

    seen={}
    for msgno in data[0].split():
        rc,data=m.fetch(msgno,'(RFC822)')
        mailcfg.ok(rc,data)
        body=email.message_from_string(data[0][1])
        h=url(str(body))
        if seen.has_key(h) == False:
            seen[h] = 1
            print h
            if DOIT: open(h)
        if DOIT: m.store(msgno, '+FLAGS', '\Deleted')

    m.close()
    m.logout()

#-----------------------------------------------------------------------
DOIT=True
# DOIT=False  # uncomment for testing
try:
    main()
except KeyboardInterrupt:
    pass
